import 'package:flutter/material.dart';

// A string list of Kentucky Derby winners
const List<String> KENTUCKY_DERBY_WINNERS = [
  "Aristides",
  "Vagrant",
  "Baden-Baden",
  "Day Star",
  "Lord Murphy",
  "Fonso",
  "Hindoo",
  "Apollo",
  "Leonatus",
  "Buchanan",
  "Joe Cotton",
  "Ben Ali",
  "Montrose",
  "Macbeth II",
  "Spokane",
  "Riley",
  "Kingman",
  "Azra",
  "Lookout",
  "Chant",
  "Halma",
  "Ben Brush",
  "Typhoon II",
  "Plaudit",
  "Manuel",
  "Lieut. Gibson",
  "His Eminence",
  "Alan-a-Dale",
  "Judge Himes",
  "Elwood",
  "Agile",
  "Sir Huon",
  "Pink Star",
  "Stone Street",
  "Wintergreen",
  "Donau",
  "Meridian",
  "Worth",
  "Donerail",
  "Old Rosebud",
  "Regret",
  "George Smith",
  "Omar Khayyam",
  "Exterminator",
  "Sir Barton",
  "Paul Jones",
  "Behave Yourself",
  "Morvich",
  "Zev",
  "Black Gold",
  "Flying Ebony",
  "Bubbling Over",
  "Whiskery",
  "Reigh Count",
  "Clyde Van Dusen",
  "Gallant Fox",
  "Twenty Grand",
  "Burgoo King",
  "Brokers Tip",
  "Cavalcade",
  "Omaha",
  "Bold Venture",
  "War Admiral",
  "Lawrin",
  "Johnstown",
  "Gallahadion",
  "Whirlaway",
  "Shut Out",
  "Count Fleet",
  "Pensive",
  "Hoop Jr.",
  "Assault",
  "Jet Pilot",
  "Citation",
  "Ponder",
  "Middleground",
  "Count Turf",
  "Hill Gail",
  "Dark Star",
  "Determine",
  "Swaps",
  "Needles",
  "Iron Liege",
  "Tim Tam",
  "Tomy Lee",
  "Venetian Way",
  "Carry Back",
  "Decidedly",
  "Chateaugay",
  "Northern Dancer",
  "Lucky Debonair",
  "Kauai King",
  "Proud Clarion",
  "Forward Pass",
  "Majestic Prince",
  "Dust Commander",
  "Canonero II",
  "Riva Ridge",
  "Secretariat",
  "Cannonade",
  "Foolish Pleasure",
  "Bold Forbes",
  "Seattle Slew",
  "Affirmed",
  "Spectacular Bid",
  "Genuine Risk",
  "Pleasant Colony",
  "Gato Del Sol",
  "Sunny's Halo",
  "Swale",
  "Spend a Buck",
  "Ferdinand",
  "Alysheba",
  "Winning Colors",
  "Sunday Silence",
  "Unbridled",
  "Strike the Gold",
  "Lil E. Tee",
  "Sea Hero",
  "Go for Gin",
  "Thunder Gulch",
  "Grindstone",
  "Silver Charm",
  "Real Quiet",
  "Charismatic",
  "Fusaichi Pegasus",
  "Monarchos",
  "War Emblem",
  "Funny Cide",
  "Smarty Jones",
  "Giacomo",
  "Barbaro",
  "Street Sense",
  "Big Brown",
  "Mine That Bird",
  "Super Saver",
  "Animal Kingdom",
  "I'll Have Another",
  "Orb",
  "California Chrome",
  "American Pharoah",
  "Nyquist",
  "Always Dreaming",
  "Justify",
  "Country House",
  "Authentic",
  "Mandaloun",
  "Rich Strike",
  "Mage",
];

enum KentuckyDerbyWinners {
  aristides,
  vagrant,
  badenBaden,
  dayStar,
  lordMurphy,
  fons,
  hindoo,
  apollo,
  leonatus,
  buchanan,
  joeCotton,
  benAli,
  montrose,
  macbethII,
  spokane,
  riley,
  kingman,
  azra,
  lookout,
  chant,
  halma,
  benBrush,
  typhoonII,
  plaudit,
  manuel,
  lieutGibson,
  hisEminence,
  alanADale,
  judgeHimes,
  elwood,
  agile,
  sirHuon,
  pinkStar,
  stoneStreet,
  wintergreen,
  donau,
  meridian,
  worth,
  donerail,
  oldRosebud,
  regret,
  georgeSmith,
  omarKhayyam,
  exterminator,
  sirBarton,
  paulJones,
  behaveYourself,
  morvich,
  zev,
  blackGold,
  flyingEbony,
  bubblingOver,
  whiskery,
  reighCount,
  clydeVanDusen,
  gallantFox,
  twentyGrand,
  burgooKing,
  brokersTip,
  cavalcade,
  omaha,
  boldVenture,
  warAdmiral,
  lawrin,
  johnstown,
  gallahadion,
  whirlaway,
  shutOut,
  countFleet,
  pensive,
  hoopJr,
  assault,
  jetPilot,
  citation,
  ponder,
  middleground,
  countTurf,
  hillGail,
  darkStar,
  determine,
  swaps,
  needles,
  ironLiege,
  timTam,
  tomyLee,
  venetianWay,
  carryBack,
  decidedly,
  chateaugay,
  northernDancer,
  luckyDebonair,
  kauaiKing,
  proudClarion,
  forwardPass,
  majesticPrince,
  dustCommander,
  canoneroII,
  rivaRidge,
  secretariat,
  cannonade,
  foolishPleasure,
  boldForbes,
  seattleSlew,
  affirmed,
  spectacularBid,
  genuineRisk,
  pleasantColony,
  gatoDelSol,
  sunnysHalo,
  swale,
  spendaBuck,
  ferdinand,
  alysheba,
  winningColors,
  sundaySilence,
  unbridled,
  strikeTheGold,
  lilETee,
  seaHero,
  goforGin,
  thunderGulch,
  grindstone,
  silverCharm,
  realQuiet,
  charismatic,
  fusaichiPegasus,
  monarchos,
  warEmblem,
  funnyCide,
  smartyJones,
  giacomo,
  barbaro,
  streetSense,
  bigBrown,
  mineThatBird,
  superSaver,
  animalKingdom,
  illHaveAnother,
  orb,
  californiaChrome,
  americanPharoah,
  nyquist,
  alwaysDreaming,
  justify,
  countryHouse,
  authentic,
  mandaloun,
  richStrike,
  mage,
}
